### ISSUE TITLE
DensePose Model Download

### ISSUE THREAD

**Issue by bravma** [JackChen890311/Simple-Magic-Animate#1]
Thanks for putting these two repos together! I was able to run magic-animate using your provided inference-script. However, I have troubles running DensePose. I have downloaded this model here: https://github.com/JackChen890311/Simple-Magic-Animate/blob/main/DensePose/configs/cse/densepose_rcnn_R_101_FPN_DL_s1x.yaml. Is this the one you used as well? Running inference for DensePose seems to work, however, the output looks weird. 
<img width="368" alt="image" src="https://github.com/JackChen890311/Simple-Magic-Animate/assets/17469737/220d446b-0973-4586-8735-e7a7d56c89b2">

**Comment by JackChen890311** [comment]
Hello,

The densepose model config I used is this one:
https://github.com/JackChen890311/Simple-Magic-Animate/blob/main/DensePose/configs/densepose_rcnn_R_101_FPN_DL_s1x.yaml

You should be able to download the checkpoint here:
https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/DENSEPOSE_IUV.md#-improved-baselines-deeplabv3-head

Choose R_101_FPN_DL_s1x under "DeepLabV3 Head" and download the model (or click [here](https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_DL_s1x/165712116/model_final_844d15.pkl)).

I'll add this to readme later as well, hope this helps!
