### ISSUE TITLE
Can't load tokenizer for 'pretrained_models/stable-diffusion-v1-5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'pretrained_models/stable-diffusion-v1-5' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

### ISSUE THREAD

**Issue by zsszyx** [JackChen890311/Simple-Magic-Animate#2]
Can't load tokenizer for 'pretrained_models/stable-diffusion-v1-5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'pretrained_models/stable-diffusion-v1-5' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by JackChen890311** [comment]
Hi,

It seems like you didn't download the pretrained models.
Please follow the 'Getting Started' section in Magic Animate Github to download pretrained models and put them in the corresponding directory. (See [here](https://github.com/magic-research/magic-animate?tab=readme-ov-file#%EF%B8%8F-getting-started))

Thanks!
